[project]
name = "algorithms"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "mypy>=1.15.0",
]

[tool.ruff]
line-length = 80
exclude = [
    "venv",
    ".vscode",
    ".pytest_cache",
    "**/migrations/**",
    ".mypy_cache",
    ".ruff_cache",
]


[tool.ruff.lint]
extend-select = ["E501", "I", "N", "PT", "PL", "RUF"]
fixable = ["ALL"]


[tool.ruff.format]
quote-style = "single"
indent-style = "space"
